version: '3'
services:
    transmission-wg:
        image: custom/transmission-wg-pia:${IMG_TAG:?error}
        build:
          context: .
        volumes:
            # Auth token is stored here
            - ${PVOL_ROOT:?error}/btTransmission/pia:/pia
            # Adding local /lib/modules to container in read-only mode for wireguard modules
            - /lib/modules:/lib/modules:ro
            # Edit this to the directory that Transmission configuration should be stored, if you'd like it persistent. Also edit TRANSMISSION_HOME to match if necessary.
            - ${PVOL_ROOT:?error}/btTransmission:/config
            # Edit this to the directory your Transmission downloads should go
            - ${PVOL_ROOT:?error}/btData:/data
            # Use host system timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/TZ:/etc/timezone:ro
        cap_add:
            - NET_ADMIN
            # SYS_MODULE might not be needed with a 5.6+ kernel?
            - SYS_MODULE
        # If the kernel module isn't available, mounting the tun device may be necessary for userspace implementations
        devices:
          - /dev/net/tun:/dev/net/tun
        environment:
            # The following env vars are required:
            - LOC=${PIA_LOC:?error}
            - USER=${PIA_USER:?error}
            - PASS=${PIA_PASS:?error}
            # The rest are optional:
            - LOCAL_NETWORK=${PIA_LOCAL_NETWORK}
            #- KEEPALIVE=25
            #- VPNDNS=8.8.8.8,8.8.4.4
            #- PORT_FORWARDING=0
            - PUID=${TRANS_PUID}
            - PGID=${TRANS_PGID}
            #- TRANSMISSION_HOME=/config
            - TRANSMISSION_LOG_FILE=/config/logs/transmission.log
            # If you use authentication in your existing settings, you will need to set them here so that the
            # port forwarding script will work correctly
            - TRANSMISSION_RPC_USERNAME=${TRANS_USER}
            - TRANSMISSION_RPC_PASSWORD=${TRANS_PSWD}
            #- WEBPROXY_ENABLED=true
            #- WEBPROXY_PORT=8888
            #- HEALTH_CHECK_HOST=google.com
        ports:
            # Transmission
            - 9091:9091
            # Tinyproxy
            #- 8888:8888
        sysctls:
            # The wg-quick script tries to set this when setting up routing, however this requires running in
            # the container with the --privileged flag set. Setting it here instead if needed means the container 
            # can be run with lower privileges. This only needs setting if strict reverse path filtering 
            # (rp_filter=1) is used.
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 90s
            timeout: 10s
            retries: 3
